baseURL = "https://seu-yuan.top/"
languageCode = "zh-cn"
title = "Ye's Blog"
theme = "PaperMod"
enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15
summaryLength = 140
defaultContentLanguage = 'zh-cn'
ShowReadingTime = true
defaultContentLanguageInSubdir = true
layoutDir = "layouts"
logFile = "Log"
pluralizeListTitles = true
relativeURLs = false
# googleAnalytics = "G-KGBJNWLV3J"      # è°·æ­Œç»Ÿè®¡ï¼Œåœ¨è¿è¡Œ hugo server ï¼ˆæµ‹è¯•ï¼‰æ—¶ä¸åŠ è½½è°·æ­Œä»£ç 
Copyright = "Copyright Â© 2021 - 2024 ChiAn Ye Â· [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) Â· [RSS](/index.xml) Â· Made with â™¥ in ğŸ‡¨ğŸ‡¦"
[minify]
disableXML = true
minifyOutput = false

[languages]
# ä¸€äº›å¯èƒ½ç”¨åˆ°çš„å›¾æ ‡ï¼Œä¾¿äºå–ç”¨
# âŒšï¸ ğŸ“± ğŸ“² ğŸ’» âŒ¨ï¸ ğŸ–¥ ğŸ–¨ ğŸ–± ğŸ–² ğŸ•¹ ğŸ—œ ğŸ’½ ğŸ’¾
# ğŸ’¿ ğŸ“€ ğŸ“¼ ğŸ“· ğŸ“¸ ğŸ“¹ ğŸ¥ ğŸ“½ ğŸ ğŸ“ â˜ï¸ ğŸ“Ÿ 
# ğŸ“  ğŸ“º ğŸ“» ğŸ™ ğŸš ğŸ› ğŸ§­ â± â² â° ğŸ•° âŒ›ï¸ â³ 
# ğŸ“¡ ğŸ”‹ ğŸª« ğŸ”Œ ğŸ’¡ ğŸ”¦ ğŸ•¯ ğŸª” ğŸ§¯ ğŸ›¢ ğŸ›ï¸ ğŸ’¸ 
# ğŸ’µ ğŸ’´ ğŸ’¶ ğŸ’· ğŸª™ ğŸ’° ğŸ’³ ğŸ’ âš–ï¸ ğŸª® ğŸªœ ğŸ§° 
# ğŸª› ğŸ”§ ğŸ”¨ âš’ ğŸ›  â› ğŸªš ğŸ”© âš™ï¸ ğŸª¤ ğŸ§± â›“ ğŸ§² 
# ğŸ”« ğŸ’£ ğŸ§¨ ğŸª“ ğŸ”ª ğŸ—¡ âš”ï¸ ğŸ›¡ ğŸš¬ âš°ï¸ ğŸª¦ âš±ï¸ ğŸº 
# ğŸ”® ğŸ“¿ ğŸ§¿ ğŸª¬ ğŸ’ˆ âš—ï¸ ğŸ”­ ğŸ”¬ ğŸ•³ ğŸ©¹ ğŸ©º ğŸ©» ğŸ©¼ 
# ğŸ’Š ğŸ’‰ ğŸ©¸ ğŸ§¬ ğŸ¦  ğŸ§« ğŸ§ª ğŸŒ¡ ğŸ§¹ ğŸª  ğŸ§º ğŸ§» ğŸš½ 
# ğŸš° ğŸš¿ ğŸ› ğŸ›€ ğŸ§¼ ğŸª¥ ğŸª’ ğŸ§½ ğŸª£ ğŸ§´ ğŸ› ğŸ”‘ ğŸ— 
# ğŸšª ğŸª‘ ğŸ›‹ ğŸ› ğŸ›Œ ğŸ§¸ ğŸª† ğŸ–¼ ğŸª ğŸªŸ ğŸ› ğŸ›’ ğŸ ğŸˆ 
# ğŸ ğŸ€ ğŸª„ ğŸª… ğŸŠ ğŸ‰ ğŸª© ğŸ ğŸ® ğŸ ğŸ§§ âœ‰ï¸ ğŸ“© 
# ğŸ“¨ ğŸ“§ ğŸ’Œ ğŸ“¥ ğŸ“¤ ğŸ“¦ ğŸ· ğŸª§ ğŸ“ª ğŸ“« ğŸ“¬ ğŸ“­ ğŸ“® 
# ğŸ“¯ ğŸ“œ ğŸ“ƒ ğŸ“„ ğŸ“‘ ğŸ§¾ ğŸ“Š ğŸ“ˆ ğŸ“‰ ğŸ—’ ğŸ—“ ğŸ“† ğŸ“… ğŸ—‘ 
# ğŸªª ğŸ“‡ ğŸ—ƒ ğŸ—³ ğŸ—„ ğŸ“‹ ğŸ“ ğŸ“‚ ğŸ—‚ ğŸ— ğŸ“° ğŸ““ ğŸ“” ğŸ“’ ğŸ“• 
# ğŸ“— ğŸ“˜ ğŸ“™ ğŸ“š ğŸ“– ğŸ”– ğŸ§· ğŸ”— ğŸ“ ğŸ–‡ ğŸ“ ğŸ“ ğŸ§® ğŸ“Œ 
# ğŸ“ âœ‚ï¸ ğŸ–Š ğŸ–‹ âœ’ï¸ ğŸ–Œ ğŸ– ğŸ“ âœï¸ ğŸ” ğŸ” ğŸ” ğŸ” ğŸ”’ ğŸ”“
[languages.zh-cn]
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 2
contentDir = 'content/zh-cn'
languageCode = "zh-CN"


[languages.en]
languageName = "English"
contentDir = 'content/en'
languageCode = 'en-US'
weight = 1


# [languages.jp]
# languageName = "æ—¥æœ¬èª"
# weight = 3

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ['HTML']

[author]
name = "ChiAn Ye"
[params]
env = "production"
description = "ChiAn Yeçš„åšå®¢,åŸºäºHugoæ­å»ºçš„åšå®¢ç½‘ç«™ï¼Œå…³äºHugoã€Papermodã€c++ã€golangã€ICPCã€CCPCã€ACMï¼Œåˆ·é¢˜ä¸»è¦åœ¨leetcode,codeforces,atcoderç­‰"
draft = "flase"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
disableShare = true
disableSpecialistPost = true
displayFullLangName = true
ShowLastMod = true
ShowShareButtons = false
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCounts = true

ShowDescription = false
ShowToc = true
hideFooter = false
VisitCount = true
TocOpen = true
comments = true
StartYear = 2023
FilingNo = ""
Reward = true
ShowStatInSectionTermList = false # åˆ—è¡¨é¡µç»Ÿè®¡æ–‡ç« ç¯‡æ•°å’Œå­—æ•°
ShowStatInArchive = false
hideMeta = false                  # å½’æ¡£é¡µç»Ÿè®¡æ–‡ç« ç¯‡æ•°å’Œå­—æ•°
Alipay = "img/alipay.png"
busuanzi = true                   # å¯ç”¨ä¸è’œå­ç»Ÿè®¡

# Giscus è¯„è®ºç³»ç»Ÿé…ç½®
[params.giscus]
enable = true
repo = "Cain-James/YYH-Hugo-Blog"
repoId = "R_kgDOJpljfQ"
category = "General"
categoryId = "DIC_kwDOJpljfc4CoOtn"
mapping = "title"
strict = 0
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "zh-CN"
loading = "lazy"

[params.profileMode]
enabled = true
title = "ç™¾å¶æ²‰ç§‹"
# subtitle = "ğŸ§¨å­¦è€Œæ—¶ä¹ ä¹‹ï¼Œä¸äº¦è¯´ä¹ï¼Ÿæœ‰æœ‹è‡ªè¿œæ–¹æ¥ï¼Œä¸äº¦ä¹ä¹ï¼Ÿ</br>ğŸ‘ğŸ¼æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢</br>ğŸ‘‡è”ç³»æ–¹å¼"
imageUrl = "img/head.jpg"
imageTitle = "å›¾ç‰‡æ ‡é¢˜"
imageWidth = 120
imageHeight = 120
[[params.profileMode.buttons]]
name = "ğŸ’» æŠ€æœ¯"
url = "./posts/tech"

[[params.profileMode.buttons]]
name = "ğŸ“¸ ç”Ÿæ´»"
url = "./posts/life"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Cain-James"

[[params.socialIcons]]
name = "QQ"
icon = ""
# url = "img/qq.png"

[[params.socialIcons]]
name = "wechat"
# url = "img/wechat.png"

[[params.socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/442037544"

[[params.socialIcons]]
name = "email"
url = "mailto:yuanyanghao2022@163.com"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

[params.label] # é¡¶éƒ¨å·¦ä¾§çš„æ–‡å­—å›¾ç‰‡
text = "Ye's Blog"
icon = "img/logo.gif"
iconHeight = 35

[params.analytics.google]
SiteVerificationTag = ""

[params.assets]
favicon = "img/logo.gif"
favicon16x16 = "img/logo.gif"
favicon32x32 = "img/logo.gif"
apple_touch_icon = "img/logo.gif"
safari_pinned_tab = "img/logo.gif"

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = true
tabWidth = 4
style = "paraiso-dark"
