[[main]]
identifier = "search"
name = "ğŸ” æœç´¢"
pageRef = "search"
weight = 10

# [[main]]
# identifier = "posts"
# name = "ğŸ“š æ–‡ç« "
# pageRef = "posts"
# weight = 30

[[main]]
identifier = ""
name = "ğŸ ä¸»é¡µ"
pageRef = "/"
weight = 11

[[main]]
identifier = "posts/tech"
name = "ğŸ”¨ æŠ€æœ¯"
pageRef = "/posts/tech"
weight = 29

[[main]]
identifier = "posts/life"
name = "ğŸ“¸ ç”Ÿæ´»"
pageRef = "/posts/life"
weight = 30

[[main]]
identifier = "tags"
name = "ğŸ“Œ æ ‡ç­¾"
pageRef = "/tags"
weight = 31

[[main]]
identifier = "archives"
name = "â±ï¸ æ—¶é—´è½´"
pageRef = "/archives"
weight = 32

[[main]]
identifier = "about"
name = "ğŸ‘©â€ğŸ’» å…³äº"
pageRef = "/about"
weight = 33
