[[main]]
identifier = "search"
name = "ğŸ” Search"
pageRef = "/search"
weight = 10

# [[main]]
# identifier = "posts"
# name = "ğŸ“š æ–‡ç« "
# pageRef = "posts"
# weight = 30

[[main]]
identifier = ""
name = "ğŸ Home"
pageRef = "/"
weight = 11

[[main]]
identifier = "posts/tech"
name = "ğŸ”¨ Tech"
pageRef = "/posts/tech"
weight = 29

[[main]]
identifier = "posts/life"
name = "ğŸ“¸ Life"
pageRef = "/posts/life"
weight = 30

[[main]]
identifier = "tags"
name = "ğŸ“Œ Tags"
pageRef = "/tags"
weight = 31

[[main]]
identifier = "archives"
name = "â±ï¸ Archives"
pageRef = "archives"
weight = 32

[[main]]
identifier = "about"
name = "ğŸ‘©â€ğŸ’» About"
pageRef = "about"
weight = 33
