baseURL = "https://seu-yuan.top/"
languageCode = "zh-cn"
title = "Ye's Blog"
theme = "PaperMod"
enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15
summaryLength = 140
defaultContentLanguage = "en"
ShowReadingTime = true
defaultContentLanguageInSubdir = true
layoutDir = "layouts"
logFile = "Log"
pluralizeListTitles = true
relativeURLs = false
[minify]
disableXML = true
minifyOutput = false

[permalinks]
post = "/:title/"
[languages]
[languages.en]
languageName = "English"
weight = 1

  [en.homeInfoParams]
  Title = "æ¬¢è¿å…‰ä¸´å°ç«™ğŸ¥‚"
  Content = """
æœ¬ç«™ä¸»è¦å†…å®¹åŒ…æ‹¬è¯»ä¹¦ç¬”è®°ã€æŠ€æœ¯ç§¯ç´¯ã€ç”Ÿæ´»æ„Ÿæ‚Ÿã€‚å¦‚æœèƒ½æœ‰å“ªäº›å†…å®¹å¯ä»¥å¸®åŠ©åˆ°ä½ ï¼Œé‚£ä¹Ÿæ˜¯æå¥½çš„ã€‚</br> ç²¾é€š CSS JavaScript PHP C C++ C# java Ruby Perl Python ç­‰å•è¯çš„æ‹¼å†™</br> ç†Ÿæ‚‰ Windows Linux Mac Android IOS ç­‰ç³»ç»Ÿçš„å¼€å…³æœº</br> ğŸƒâ€â™‚ï¸ è·‘æ­¥ ğŸ®ï¸ æ¸¸æˆ ğŸ§ éŸ³ä¹ ğŸ“º åŠ¨æ¼« 
"""

[[languages.en.menu.main]]
identifier = "search"
name = "ğŸ” æœç´¢"
url = "search"
weight = 10

[[languages.en.menu.main]]
identifier = "posts"
name = "ğŸ“š æ–‡ç« "
url = "posts"
weight = 30

[[languages.en.menu.main]]
identifier = "archives"
name = "ğŸ“ˆ å½’æ¡£"
url = "archives"
weight = 50


[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = ['HTML']

[params]
env = "production"
description = ""

author = "ChiAn Ye"
draft = "flase"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
disableShare = true
ShowShareButtons = false
ShowReadingTime = false
disableSpecialistPost = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true
StartYear = 2_020
FilingNo = ""
Reward = true
WechatPay = "img/wechat_pay.png"
Alipay = "img/alipay.png"
    [params.profileMode]
    enabled = true
    title = "Yuan's Blog"
    subtitle = ""
    imageUrl = "img/head.jpg"
    imageTitle = "å›¾ç‰‡æ ‡é¢˜"
    imageWidth = 120
    imageHeight = 120
    
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Cain-James"

    [[params.socialIcons]]
    name = "QQ"
    url = "img/qq.png"

    [[params.socialIcons]]
    name = "WeChat"
    url = "img/wechat.png"

    [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/442037544"

    [[params.socialIcons]]
    name = "email"
    url = "mailto:yuanyanghao2022@163.com"

    [[params.socialIcons]]
    name = "RSS"
    url = "index.xml"

    [params.label]
    text = "Ye's Blog"
    icon = "img/avatar.gif"
    iconHeight = 35

[params.analytics.google]
SiteVerificationTag = ""

  [params.assets]
  favicon = "img/avatar.gif"
  favicon16x16 = "img/avatar.gif"
  favicon32x32 = "img/avatar.gif"
  apple_touch_icon = "img/avatar.gif"
  safari_pinned_tab = "img/avatar.gif"

  [params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = true
tabWidth = 4
style = "paraiso-dark"

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
