baseURL = "https://seu-yuan.top/"
languageCode = "zh-cn"
title = "Ye's Blog"
theme = "PaperMod"
enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15
summaryLength = 140
defaultContentLanguage = "zh"
ShowReadingTime = true
defaultContentLanguageInSubdir = true
layoutDir = "layouts"
logFile = "Log"
pluralizeListTitles = true
relativeURLs = false
googleAnalytics = "UA-123-45"
Copyright = "Yuan"
[minify]
disableXML = true
minifyOutput = false

[languages]
# ä¸€äº›å¯èƒ½ç”¨åˆ°çš„å›¾æ ‡ï¼Œä¾¿äºå–ç”¨
# âŒšï¸ ğŸ“± ğŸ“² ğŸ’» âŒ¨ï¸ ğŸ–¥ ğŸ–¨ ğŸ–± ğŸ–² ğŸ•¹ ğŸ—œ ğŸ’½ ğŸ’¾
# ğŸ’¿ ğŸ“€ ğŸ“¼ ğŸ“· ğŸ“¸ ğŸ“¹ ğŸ¥ ğŸ“½ ğŸ ğŸ“ â˜ï¸ ğŸ“Ÿ 
# ğŸ“  ğŸ“º ğŸ“» ğŸ™ ğŸš ğŸ› ğŸ§­ â± â² â° ğŸ•° âŒ›ï¸ â³ 
# ğŸ“¡ ğŸ”‹ ğŸª« ğŸ”Œ ğŸ’¡ ğŸ”¦ ğŸ•¯ ğŸª” ğŸ§¯ ğŸ›¢ ğŸ›ï¸ ğŸ’¸ 
# ğŸ’µ ğŸ’´ ğŸ’¶ ğŸ’· ğŸª™ ğŸ’° ğŸ’³ ğŸ’ âš–ï¸ ğŸª® ğŸªœ ğŸ§° 
# ğŸª› ğŸ”§ ğŸ”¨ âš’ ğŸ›  â› ğŸªš ğŸ”© âš™ï¸ ğŸª¤ ğŸ§± â›“ ğŸ§² 
# ğŸ”« ğŸ’£ ğŸ§¨ ğŸª“ ğŸ”ª ğŸ—¡ âš”ï¸ ğŸ›¡ ğŸš¬ âš°ï¸ ğŸª¦ âš±ï¸ ğŸº 
# ğŸ”® ğŸ“¿ ğŸ§¿ ğŸª¬ ğŸ’ˆ âš—ï¸ ğŸ”­ ğŸ”¬ ğŸ•³ ğŸ©¹ ğŸ©º ğŸ©» ğŸ©¼ 
# ğŸ’Š ğŸ’‰ ğŸ©¸ ğŸ§¬ ğŸ¦  ğŸ§« ğŸ§ª ğŸŒ¡ ğŸ§¹ ğŸª  ğŸ§º ğŸ§» ğŸš½ 
# ğŸš° ğŸš¿ ğŸ› ğŸ›€ ğŸ§¼ ğŸª¥ ğŸª’ ğŸ§½ ğŸª£ ğŸ§´ ğŸ› ğŸ”‘ ğŸ— 
# ğŸšª ğŸª‘ ğŸ›‹ ğŸ› ğŸ›Œ ğŸ§¸ ğŸª† ğŸ–¼ ğŸª ğŸªŸ ğŸ› ğŸ›’ ğŸ ğŸˆ 
# ğŸ ğŸ€ ğŸª„ ğŸª… ğŸŠ ğŸ‰ ğŸª© ğŸ ğŸ® ğŸ ğŸ§§ âœ‰ï¸ ğŸ“© 
# ğŸ“¨ ğŸ“§ ğŸ’Œ ğŸ“¥ ğŸ“¤ ğŸ“¦ ğŸ· ğŸª§ ğŸ“ª ğŸ“« ğŸ“¬ ğŸ“­ ğŸ“® 
# ğŸ“¯ ğŸ“œ ğŸ“ƒ ğŸ“„ ğŸ“‘ ğŸ§¾ ğŸ“Š ğŸ“ˆ ğŸ“‰ ğŸ—’ ğŸ—“ ğŸ“† ğŸ“… ğŸ—‘ 
# ğŸªª ğŸ“‡ ğŸ—ƒ ğŸ—³ ğŸ—„ ğŸ“‹ ğŸ“ ğŸ“‚ ğŸ—‚ ğŸ— ğŸ“° ğŸ““ ğŸ“” ğŸ“’ ğŸ“• 
# ğŸ“— ğŸ“˜ ğŸ“™ ğŸ“š ğŸ“– ğŸ”– ğŸ§· ğŸ”— ğŸ“ ğŸ–‡ ğŸ“ ğŸ“ ğŸ§® ğŸ“Œ 
# ğŸ“ âœ‚ï¸ ğŸ–Š ğŸ–‹ âœ’ï¸ ğŸ–Œ ğŸ– ğŸ“ âœï¸ ğŸ” ğŸ” ğŸ” ğŸ” ğŸ”’ ğŸ”“
[languages.zh]
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 1
    [[languages.zh.menu.main]]
    identifier = "search"
    name = "ğŸ” æœç´¢"
    url = "search"
    weight = 10

    # [[languages.zh.menu.main]]
    # identifier = "posts"
    # name = "ğŸ“š æ–‡ç« "
    # url = "posts"
    # weight = 30

    [[languages.zh.menu.main]]
    identifier = ""
    name = "ğŸ ä¸»é¡µ"
    url = "/"
    weight = 11

    [[languages.zh.menu.main]]
    identifier = "posts/tech"
    name = "ğŸ”¨ æŠ€æœ¯"
    url = "posts/tech"
    weight = 29

    [[languages.zh.menu.main]]
    identifier = "posts/life"
    name = "ğŸ“¸ ç”Ÿæ´»"
    url = "posts/life"
    weight = 30

    [[languages.zh.menu.main]]
    identifier = "tags"
    name = "ğŸ“Œ æ ‡ç­¾"
    url = "tags"
    weight = 31

    [[languages.zh.menu.main]]
    identifier = "archives"
    name = "â±ï¸ æ—¶é—´è½´"
    url = "archives"
    weight = 32

    [[languages.zh.menu.main]]
    identifier = "about"
    name = "ğŸ‘©â€ğŸ’» å…³äº"
    url = "about"
    weight = 33

# [languages.en]
# languageName = "English"
# weight = 2

# [languages.jp]
# languageName = "æ—¥æœ¬èª"
# weight = 3

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = ['HTML']

[params]
env = "production"
description = "è¿™æ˜¯æˆ‘çš„ç¬¬ä¸€ä¸ªåŸºäºHugoæ­å»ºçš„åšå®¢ç½‘ç«™"

author = "ChiAn Ye"
draft = "flase"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
disableShare = true
disableSpecialistPost = true
displayFullLangName = true
ShowLastMod = true
ShowShareButtons = false
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCounts = true
ShowToc = true
hideFooter = false
VisitCount = true
TocOpen = true
comments = true
StartYear = 2_020
FilingNo = ""
Reward = true
Alipay = "img/alipay.png"
    [params.profileMode]
    enabled = true
    title = "Yuan's Blog"
    subtitle = "ğŸ§¨å­¦è€Œæ—¶ä¹ ä¹‹ï¼Œä¸äº¦è¯´ä¹ï¼Ÿæœ‰æœ‹è‡ªè¿œæ–¹æ¥ï¼Œä¸äº¦ä¹ä¹ï¼Ÿ</br>ğŸ‘ğŸ¼æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢</br>ğŸ‘‡è”ç³»æ–¹å¼"
    imageUrl = "img/head.jpg"
    imageTitle = "å›¾ç‰‡æ ‡é¢˜"
    imageWidth = 120
    imageHeight = 120
    [[params.profileMode.buttons]]
    name = "ğŸ’» æŠ€æœ¯"
    url = "/posts/tech"

    [[params.profileMode.buttons]]
    name = "ğŸ“¸ ç”Ÿæ´»"
    url = "/posts/life"
    
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Cain-James"

    [[params.socialIcons]]
    name = "QQ"
    url = "img/qq.png"

    [[params.socialIcons]]
    name = "Weixin"
    url = "img/wechat.png"

    [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/442037544"

    [[params.socialIcons]]
    name = "email"
    url = "mailto:yuanyanghao2022@163.com"

    [[params.socialIcons]]
    name = "RSS"
    url = "index.xml"

    [params.label]
    text = "Ye's Blog"
    icon = "img/logo.gif"
    iconHeight = 35


[params.analytics.google]
SiteVerificationTag = ""

  [params.assets]
  favicon = "img/logo.gif"
  favicon16x16 = "img/logo.gif"
  favicon32x32 = "img/logo.gif"
  apple_touch_icon = "img/logo.gif"
  safari_pinned_tab = "img/logo.gif"

  [params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = true
tabWidth = 4
style = "paraiso-dark"

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
